In [1]:
import numpy as np

Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
n = 10
np.arange(n, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
n = 10
m = np.diag(np.arange(n,0,-1))
sum_diagonal = sum(m[i][i] for i in range(n))
print(sum_diagonal)

55


Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [4]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [5]:
b = np.array( [4, 12, -3] )

In [6]:
from numpy import linalg

In [7]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

Задача 4

In [8]:
import matplotlib.pyplot as plt

In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [10]:
rez=[]
f = np.array([0, 1, 2, 0, 0, 0])
fLength = np.linalg.norm(f)
for user_id, user_vector in enumerate(users_stats):
    e = [user_vector]
    eLength = np.linalg.norm(e)
    rez.append(((np.dot(e, f) / (eLength*fLength)), user_id))
print(max(rez))

(array([0.9486833]), 7)
